language: node_js
node_js:
  - '13'
  - '12'
  - '10'
script:
  - "npm run test-travis"
after_script:
  - "npm install coveralls@3 && cat coverage/lcov.info | coveralls"
notifications:
  email: a@alexandresaiz.com
